services:
  - type: web
    name: fyvio-unified
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt &&
      cd frontend &&
      npm install &&
      npm run build
    startCommand: uvicorn backend.fastapi.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    scaling:
      minInstances: 1
      maxInstances: 1